name: Hello World

# Trigger: run this workflow on every push
#on: [push]
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World from GitHub Actions!"
